[package]
name = "telemetry-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

opentelemetry = { version = "0.27.1", features = ["trace", "metrics", "logs"] }
opentelemetry_sdk = { version = "0.27.1", features = ["metrics", "trace", "logs", "rt-tokio", "tracing", "async-trait"] }
opentelemetry-otlp = { version = "0.27.0", features = ["trace", "metrics", "logs", "populate-logs-event-name", "grpc-tonic"] }
opentelemetry-stdout = {version = "0.27.0", features = ["trace", "metrics", "logs"]}
opentelemetry-semantic-conventions = {version = "0.27.0", features = ["default", "semconv_experimental"] }
opentelemetry-appender-tracing = "0.27.0"

tracing = { version = "0.1.41", default-features = false, features = ["std", "attributes", "async-await", "tracing-attributes"] }
tracing-subscriber = { version = "0.3.19", default-features = false, features = ["registry", "std", "chrono", "ansi"] }
tracing-opentelemetry = { version = "0.28.0", features = ["metrics", "tracing-log", "async-trait"] }
