receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
  otlphttp/traces:
    endpoint: http://tempo:4418
  otlphttp/metrics:
    endpoint: http://mimir:9009/api/v1/otlp
  debug/traces:
    verbosity: detailed
  debug/logs:
    verbosity: detailed
  debug/metrics:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/traces]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/metrics]
